name: dr_drivings_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.7.2

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  firebase_core: 3.12.1
  firebase_auth: ^5.5.0
  cloud_firestore: ^5.6.5
  camera: ^0.11.1
  google_mlkit_text_recognition: 0.14.0
  animations: ^2.0.11
  provider: ^6.1.2
  google_fonts: ^6.2.1
  lottie: ^3.3.1
  flutter_hooks: ^0.21.2
  permission_handler: ^12.0.0+1
  cupertino_icons: ^1.0.8
  flutter_tts: ^4.2.2  
  flutter_blue_plus: ^1.6.0  
  geolocator: ^13.0.2
  image_picker: ^1.1.2
  google_maps_flutter: ^2.5.0
  firebase_database: ^11.3.4
  webview_flutter: ^4.11.0
  webview_flutter_android: ^4.4.0
  webview_flutter_plus: ^0.4.15
  fl_chart: ^0.64.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: 0.14.3
  video_player: ^2.9.5

flutter:
  uses-material-design: true
  assets:
    - assets/animations/intro.json
    - assets/photos/drdrivings.jpg
    - assets/photos/license_sample.jpg
    - assets/photos/first_gear.png
    - assets/videos/car_intro_1.mp4
    - assets/index.html

    